# Generated by Django 5.1.2 on 2024-12-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('ACH Transfer', 'Automated Clearing House (ACH) Transfer'), ('Cash', 'Cash'), ('Paper Check', 'Paper Check'), ('eCheck', 'eCheck'), ('Digital Payment', 'Digital Payment')], max_length=50),
        ),
    ]
